name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle Wrapper
      run: |
        gradle wrapper --gradle-version 7.5 --distribution-type bin
        
    - name: Make gradlew executable
      run: chmod +x ./gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    - name: Build Release APK
      run: ./gradlew assembleRelease
        
    - name: Upload APK Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-apks
        path: |
          app/build/outputs/apk/debug/
          app/build/outputs/apk/release/
        retention-days: 30

    - name: Create GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: app/build/outputs/apk/release/app-release.apk
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        body: |
          🚀 Умный AI Помощник для Android
          
          📱 **Функции:**
          - Текстовый и голосовой ввод
          - Локальная AI модель  
          - Поиск в интернете
          - Обработка команд
          
          ⬇️ **Скачать APK:** `app-release.apk`
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
